"""
Tender Intelligence Agent Dashboard.

Reads ONLY the JSON generated by GitHub Actions:
- data/live_tenders.json
- data/health.json

No demo, fake, fallback, or sample tender data.
"""

import csv
import io
import json
import os
from datetime import datetime, timezone

import streamlit as st

PROJECT_ROOT = os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))
)

LIVE_DATA_FILE = os.path.join(
    PROJECT_ROOT,
    "data",
    "live_tenders.json",
)

HEALTH_FILE = os.path.join(
    PROJECT_ROOT,
    "data",
    "health.json",
)

st.set_page_config(
    page_title="Tender Intelligence Agent",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded",
)


def load_json(file_path: str, fallback: dict) -> dict:
    if not os.path.exists(file_path):
        return fallback

    try:
        with open(file_path, "r", encoding="utf-8") as file:
            return json.load(file)
    except Exception as error:
        return {
            **fallback,
            "status": "READ_ERROR",
            "message": f"Unable to read {os.path.basename(file_path)}: {error}",
        }


def parse_time(value: str):
    if not value:
        return None

    try:
        return datetime.fromisoformat(
            str(value).replace("Z", "+00:00")
        )
    except ValueError:
        return None


def time_ago(value: str) -> str:
    timestamp = parse_time(value)

    if not timestamp:
        return "Unknown"

    if timestamp.tzinfo is None:
        timestamp = timestamp.replace(tzinfo=timezone.utc)

    diff = datetime.now(timezone.utc) - timestamp
    seconds = int(diff.total_seconds())

    if seconds < 0:
        return "Clock mismatch"

    if seconds < 60:
        return "Just now"

    if seconds < 3600:
        return f"{seconds // 60} minute(s) ago"

    if seconds < 86400:
        return f"{seconds // 3600} hour(s) ago"

    return f"{seconds // 86400} day(s) ago"


def build_rows(tenders: list[dict]):
    """
    UI-level second safety filter.
    Even if bad data somehow enters JSON, it will not be displayed.
    """

    allowed_categories = {
        "Charging point operations",
        "Solar",
        "Bus operations (gross cost only)",
        "Bus body building",
    }

    rows = []
    rejected_net_cost = 0
    rejected_wrong_category = 0

    for tender in tenders:
        if not isinstance(tender, dict):
            continue

        category = str(tender.get("category", "")).strip()

        if category not in allowed_categories:
            rejected_wrong_category += 1
            continue

        is_net_cost = bool(tender.get("is_net_cost", False))

        # Critical requirement:
        # Never display a Net Cost Bus Operations tender.
        if (
            category == "Bus operations (gross cost only)"
            and is_net_cost
        ):
            rejected_net_cost += 1
            continue

        rows.append(
            {
                "Tender Title": tender.get("title", "NOT SURE"),
                "Category": category,
                "Closing Date": tender.get("closing_date", "NOT SURE"),
                "Issued By": tender.get("issued_by", "NOT SURE"),
                "Qualification Criteria": tender.get(
                    "qualification_criteria",
                    "NOT SURE",
                ),
                "Eligibility": tender.get(
                    "eligibility_status",
                    "NOT SURE",
                ),
                "Cost Model": (
                    "✅ GROSS COST VERIFIED"
                    if category == "Bus operations (gross cost only)"
                    else "Not applicable"
                ),
                "Open Today": (
                    "🟢 YES"
                    if tender.get("is_open_now", False)
                    else "⚪ NOT CONFIRMED"
                ),
                "Confidence": tender.get("confidence", "LOW"),
                "Evidence": tender.get("evidence", "NOT SURE"),
                "Source URL": tender.get("source_url", ""),
                "Found At": str(
                    tender.get("found_at", "NOT SURE")
                )[:19],
            }
        )

    return rows, rejected_net_cost, rejected_wrong_category


def main():
    live_data = load_json(
        LIVE_DATA_FILE,
        {
            "data_source": "NO_LIVE_DATA_FILE",
            "generated_at": None,
            "record_count": 0,
            "tenders": [],
        },
    )

    health_data = load_json(
        HEALTH_FILE,
        {
            "status": "NO_HEALTH_FILE",
            "message": "No successful pipeline run has created health data yet.",
            "updated_at": None,
            "details": [],
        },
    )

    tenders = live_data.get("tenders", [])

    if not isinstance(tenders, list):
        tenders = []

    rows, blocked_net_cost, blocked_categories = build_rows(tenders)

    st.title("Tender Intelligence Agent — Live Monitor")

    st.caption(
        "Autonomous tender monitoring for Charging Point Operations, "
        "Solar, Gross Cost Bus Operations, and Bus Body Building."
    )

    # ---------------- SIDEBAR ----------------

    with st.sidebar:
        st.header("System Health")

        status = str(health_data.get("status", "UNKNOWN")).upper()
        message = health_data.get("message", "")
        updated_at = health_data.get("updated_at")

        if status == "SUCCESS":
            st.success("🟢 SYSTEM HEALTHY")
            st.write(message)

        elif status == "SUCCESS_ZERO_RESULTS":
            st.warning("🟡 SCAN COMPLETED — ZERO RESULTS")
            st.write(message)

        elif status == "FAILED":
            st.error("🔴 PIPELINE FAILED")
            st.write(message)

        elif status in {"NO_HEALTH_FILE", "READ_ERROR"}:
            st.warning("🟡 WAITING FOR FIRST SCAN")
            st.write(message)

        else:
            st.info(f"Status: {status}")
            st.write(message)

        st.caption(
            f"Last pipeline update: {time_ago(updated_at)}"
        )

        st.divider()

        st.subheader("Data Feed")

        generated_at = live_data.get("generated_at")

        if generated_at:
            st.success("🟢 REAL DATA FILE AVAILABLE")
            st.caption(
                f"Last successful data output: {time_ago(generated_at)}"
            )
        else:
            st.warning("No real tender JSON file has been generated yet.")

        st.divider()

        st.subheader("Compliance Rules")

        st.markdown(
            """
- ✅ Four approved categories only  
- ✅ Closed tenders rejected  
- ✅ Net Cost Bus tenders rejected  
- ✅ Gross Cost evidence required for Bus Operations  
- ✅ Unknown data shown as `NOT SURE`  
- ✅ Original source links retained  
- ✅ Pipeline health is visible  
            """
        )

        st.divider()

        st.markdown(
            "[Run the GitHub Action manually](https://github.com/offoabhii/tender-intelligence-agent/actions)"
        )

    # ---------------- METRICS ----------------

    currently_open = sum(
        1 for row in rows
        if row["Open Today"] == "🟢 YES"
    )

    high_confidence = sum(
        1 for row in rows
        if str(row["Confidence"]).upper() == "HIGH"
    )

    categories_found = len(
        set(row["Category"] for row in rows)
    )

    metric_1, metric_2, metric_3, metric_4 = st.columns(4)

    metric_1.metric("Verified Real Tenders", len(rows))
    metric_2.metric("Currently Open", currently_open)
    metric_3.metric("Categories Covered", categories_found)
    metric_4.metric("High Confidence", high_confidence)

    st.divider()

    st.info(
        "🛡️ **Gross Cost rule:** Bus-operation tenders appear only where "
        "the system finds evidence of a Gross Cost model. Net Cost and "
        "unclear contract models are rejected."
    )

    if blocked_net_cost > 0:
        st.warning(
            f"{blocked_net_cost} Net Cost Bus tender(s) were blocked."
        )

    if blocked_categories > 0:
        st.caption(
            f"{blocked_categories} non-approved category item(s) were filtered."
        )

    # ---------------- TABLE ----------------

    st.subheader("Verified Open Tender Feed")

    if not rows:
        st.warning(
            "No verified real tenders are available from the latest scan."
        )

        st.markdown(
            """
This is an honest result, not demo data.

Possible reasons:

1. GitHub Actions has not completed its first successful scan.
2. Tavily returned no usable current tender pages.
3. Tender results were old, closed, irrelevant, or had no verifiable deadline.
4. Bus-operation results were Net Cost or had an unclear contract model.
5. Gemini/Tavily API failed; check the System Health panel and Actions logs.
            """
        )

        return

    categories = sorted(
        set(row["Category"] for row in rows)
    )

    selected_categories = st.multiselect(
        "Filter by Category",
        options=categories,
        default=categories,
    )

    filtered_rows = [
        row for row in rows
        if row["Category"] in selected_categories
    ]

    st.dataframe(
        filtered_rows,
        use_container_width=True,
        hide_index=True,
        column_config={
            "Tender Title": st.column_config.TextColumn(
                "Tender Title",
                width="large",
            ),
            "Qualification Criteria": st.column_config.TextColumn(
                "Qualification Criteria",
                width="large",
            ),
            "Evidence": st.column_config.TextColumn(
                "Source Evidence",
                width="large",
            ),
            "Source URL": st.column_config.LinkColumn(
                "Original Tender Source",
                display_text="Open source",
                help="Open this source URL to cross-check the tender.",
            ),
        },
    )

    # ---------------- CSV ----------------

    if filtered_rows:
        csv_buffer = io.StringIO()

        writer = csv.DictWriter(
            csv_buffer,
            fieldnames=filtered_rows[0].keys(),
        )

        writer.writeheader()
        writer.writerows(filtered_rows)

        st.download_button(
            label="Download Verified Results as CSV",
            data=csv_buffer.getvalue().encode("utf-8"),
            file_name=(
                f"verified_tenders_"
                f"{datetime.now().strftime('%Y%m%d_%H%M')}.csv"
            ),
            mime="text/csv",
        )

    with st.expander("How to cross-verify a tender"):
        st.markdown(
            """
1. Click **Open source** in the table.  
2. Compare the tender title, issuing authority, and closing date.  
3. For Bus Operations, verify the source explicitly confirms **Gross Cost**.  
4. If a source does not state a field clearly, the dashboard should display `NOT SURE`.  
5. This application contains no hardcoded demo/sample tender records.  
            """
        )


if __name__ == "__main__":
    main()
