"""
Tender Intelligence Agent Dashboard

Data source:
- data/live_tenders.json
- Generated by GitHub Actions through run_agent.py

This dashboard never creates sample/fake tenders.
If no real data is available, it explicitly shows that status.
"""

import json
import os
import sys
from datetime import datetime, timezone

import streamlit as st

# Allow imports when running locally or on Streamlit Cloud.
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from config import CATEGORIES_ALLOWED

# ---------------------------------------------------------
# STREAMLIT PAGE CONFIG
# ---------------------------------------------------------

st.set_page_config(
    page_title="Tender Intelligence Agent",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded",
)

LIVE_DATA_FILE = os.path.join(PROJECT_ROOT, "data", "live_tenders.json")
HEALTH_LOG_FILE = os.path.join(PROJECT_ROOT, "system_health.log")

# ---------------------------------------------------------
# HELPERS
# ---------------------------------------------------------

def parse_datetime(value):
    """Safely parse ISO date/time strings from pipeline JSON."""
    if not value:
        return None

    try:
        value = str(value).replace("Z", "+00:00")
        return datetime.fromisoformat(value)
    except Exception:
        return None


def time_ago(value):
    """Convert an ISO timestamp to a readable age."""
    dt = parse_datetime(value)

    if not dt:
        return "Unknown"

    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)

    now = datetime.now(timezone.utc)
    difference = now - dt
    seconds = int(difference.total_seconds())

    if seconds < 0:
        return "Time appears to be in the future"

    if seconds < 60:
        return "Just now"

    if seconds < 3600:
        return f"{seconds // 60} minutes ago"

    if seconds < 86400:
        return f"{seconds // 3600} hours ago"

    return f"{seconds // 86400} days ago"


def load_live_tenders():
    """
    Reads actual output from GitHub Actions.

    Expected JSON format:
    {
      "generated_at": "...",
      "record_count": 2,
      "data_source": "LIVE_FETCHED_DATA",
      "tenders": [...]
    }
    """
    if not os.path.exists(LIVE_DATA_FILE):
        return {
            "generated_at": None,
            "record_count": 0,
            "data_source": "NO_FILE",
            "tenders": [],
            "error": (
                "No live data file exists yet. "
                "GitHub Actions must complete one successful scan first."
            ),
        }

    try:
        with open(LIVE_DATA_FILE, "r", encoding="utf-8") as file:
            payload = json.load(file)

        # Supports both the new object format and an older raw-list format.
        if isinstance(payload, list):
            return {
                "generated_at": None,
                "record_count": len(payload),
                "data_source": "LIVE_FETCHED_DATA",
                "tenders": payload,
                "error": None,
            }

        tenders = payload.get("tenders", [])

        if not isinstance(tenders, list):
            tenders = []

        return {
            "generated_at": payload.get("generated_at"),
            "record_count": payload.get("record_count", len(tenders)),
            "data_source": payload.get("data_source", "LIVE_FETCHED_DATA"),
            "tenders": tenders,
            "error": None,
        }

    except json.JSONDecodeError:
        return {
            "generated_at": None,
            "record_count": 0,
            "data_source": "INVALID_JSON",
            "tenders": [],
            "error": "The live data file exists but contains invalid JSON.",
        }

    except Exception as error:
        return {
            "generated_at": None,
            "record_count": 0,
            "data_source": "READ_ERROR",
            "tenders": [],
            "error": f"Could not read live data: {error}",
        }


def read_last_health_log():
    """Reads latest health message if system_health.log exists."""
    if not os.path.exists(HEALTH_LOG_FILE):
        return None

    try:
        with open(HEALTH_LOG_FILE, "r", encoding="utf-8") as file:
            lines = [line.strip() for line in file.readlines() if line.strip()]

        return lines[-1] if lines else None
    except Exception:
        return None


def is_open_tender(tender):
    """Accept supports both old and new pipeline field names."""
    return bool(
        tender.get("is_open_now", tender.get("is_currently_open", False))
    )


def is_net_cost_tender(tender):
    """Accept supports both old and new pipeline field names."""
    return bool(
        tender.get("is_net_cost", tender.get("is_net_cost_model", False))
    )


def build_display_rows(tenders):
    """
    Convert raw tender records into dashboard rows.

    Important:
    - Net Cost bus tenders are not displayed.
    - Non-whitelisted categories are not displayed.
    """
    rows = []
    rejected_net_cost_count = 0
    rejected_category_count = 0

    for tender in tenders:
        if not isinstance(tender, dict):
            continue

        category = str(tender.get("category", "")).strip()

        # Strict category enforcement in UI as second defense layer.
        if category not in CATEGORIES_ALLOWED:
            rejected_category_count += 1
            continue

        # Absolute employer requirement:
        # Net Cost Bus Operations must never surface as an opportunity.
        if (
            category == "Bus operations (gross cost only)"
            and is_net_cost_tender(tender)
        ):
            rejected_net_cost_count += 1
            continue

        closing_date = tender.get("closing_date") or "NOT SURE"
        issuer = tender.get("issued_by") or "NOT SURE"
        qualification = tender.get("qualification_criteria") or "NOT SURE"
        eligibility = tender.get("eligibility_status") or "NOT SURE"
        confidence = (
            tender.get("extraction_confidence")
            or tender.get("confidence_score")
            or "NOT SURE"
        )
        source_url = tender.get("source_url") or "NOT SURE"

        cost_model = "N/A"

        if category == "Bus operations (gross cost only)":
            cost_model = "✅ GROSS COST VERIFIED"
        elif is_net_cost_tender(tender):
            cost_model = "⚠️ NET COST FLAG"
        else:
            cost_model = "Not applicable"

        rows.append(
            {
                "Tender Title": tender.get("title") or "NOT SURE",
                "Category": category,
                "Closing Date": str(closing_date),
                "Issued By": str(issuer),
                "Qualification Criteria": str(qualification),
                "Eligibility": str(eligibility),
                "Cost Model Check": cost_model,
                "Open Today": "🟢 YES" if is_open_tender(tender) else "⚪ NOT CONFIRMED",
                "Confidence": str(confidence),
                "Source URL": str(source_url),
                "Found At": str(tender.get("found_at") or "NOT SURE")[:19],
            }
        )

    return rows, rejected_net_cost_count, rejected_category_count


# ---------------------------------------------------------
# MAIN APP
# ---------------------------------------------------------

def main():
    payload = load_live_tenders()

    generated_at = payload["generated_at"]
    tenders = payload["tenders"]
    error_message = payload["error"]

    display_rows, blocked_net_cost, blocked_categories = build_display_rows(tenders)

    # ---------------- HEADER ----------------

    st.title("Tender Intelligence Agent — Live Monitor")
    st.caption(
        "Autonomous tender discovery for Charging Point Operations, Solar, "
        "Gross Cost Bus Operations, and Bus Body Building."
    )

    # ---------------- SIDEBAR / HEALTH ----------------

    with st.sidebar:
        st.header("System Health")

        if error_message:
            st.error("🔴 DATA PIPELINE ISSUE")
            st.write(error_message)
            st.caption(
                "The dashboard is intentionally showing this message rather than "
                "pretending data is available."
            )

        elif generated_at:
            st.success("🟢 LIVE DATA FILE AVAILABLE")
            st.write(f"**Last scan:** {time_ago(generated_at)}")
            st.caption(f"UTC timestamp: {generated_at}")

            if len(display_rows) > 0:
                st.success(f"{len(display_rows)} real matching tender(s) available.")
            else:
                st.warning(
                    "Latest scan completed, but no matching open tenders were found."
                )

        else:
            st.warning("🟡 WAITING FOR FIRST SUCCESSFUL SCAN")
            st.write(
                "Run the GitHub Actions workflow once, then refresh this page."
            )

        st.divider()

        st.subheader("Latest Pipeline Message")
        last_log = read_last_health_log()

        if last_log:
            st.code(last_log, language=None)
        else:
            st.caption("No health log found yet.")

        st.divider()

        st.subheader("Rules Enforced")
        st.markdown(
            """
- ✅ Four categories only  
- ✅ Net Cost bus tenders rejected  
- ✅ Only open/current opportunities intended  
- ✅ Missing data is shown as `NOT SURE`  
- ✅ Source links retained for verification  
- ✅ Failure is shown clearly; no silent blank page  
            """
        )

        st.divider()

        st.markdown(
            "[Run GitHub Action manually](https://github.com/offoabhii/tender-intelligence-agent/actions)"
        )

    # ---------------- METRICS ----------------

    open_count = sum(
        1 for tender in tenders
        if is_open_tender(tender)
        and tender.get("category") in CATEGORIES_ALLOWED
        and not (
            tender.get("category") == "Bus operations (gross cost only)"
            and is_net_cost_tender(tender)
        )
    )

    high_confidence_count = sum(
        1
        for row in display_rows
        if str(row.get("Confidence", "")).upper() == "HIGH"
    )

    categories_found = len(set(row["Category"] for row in display_rows))

    metric_1, metric_2, metric_3, metric_4 = st.columns(4)
    metric_1.metric("Real Tenders Found", len(display_rows))
    metric_2.metric("Currently Open", open_count)
    metric_3.metric("Categories Covered", categories_found)
    metric_4.metric("High Confidence", high_confidence_count)

    # ---------------- COMPLIANCE BANNER ----------------

    st.divider()

    st.info(
        "🛡️ **Strict rule:** Bus-operation tenders are surfaced only if they are "
        "not identified as Net Cost. Net Cost bus contracts are rejected before display."
    )

    if blocked_net_cost > 0:
        st.warning(
            f"{blocked_net_cost} Net Cost bus tender(s) were blocked and not displayed."
        )

    if blocked_categories > 0:
        st.caption(
            f"{blocked_categories} item(s) outside the four approved categories were filtered."
        )

    # ---------------- TENDER TABLE ----------------

    st.subheader("Live Open Tender Feed")

    if error_message:
        st.error(
            "Live data cannot be verified because the pipeline output file could not be loaded."
        )
        return

    if not display_rows:
        st.warning(
            "No real matching open tenders are available from the latest scan."
        )

        st.markdown(
            """
This is an honest empty state, not demo data.

Possible reasons:
1. The first GitHub Actions scan has not completed yet.
2. The sources returned no tenders matching the four approved categories.
3. The portals blocked the data request or search provider returned no usable results.
4. All detected Bus Operations tenders were Net Cost and therefore correctly rejected.

Check the **System Health** panel and GitHub Actions logs.
            """
        )
        return

    available_categories = sorted(
        list(set(row["Category"] for row in display_rows))
    )

    selected_categories = st.multiselect(
        "Filter by category",
        options=available_categories,
        default=available_categories,
    )

    filtered_rows = [
        row for row in display_rows
        if row["Category"] in selected_categories
    ]

    st.dataframe(
        filtered_rows,
        use_container_width=True,
        hide_index=True,
        column_config={
            "Tender Title": st.column_config.TextColumn(
                "Tender Title", width="large"
            ),
            "Qualification Criteria": st.column_config.TextColumn(
                "Qualification Criteria", width="large"
            ),
            "Source URL": st.column_config.LinkColumn(
                "Original Tender Source",
                help="Open source portal to cross-check the tender.",
                display_text="Open source",
            ),
            "Cost Model Check": st.column_config.TextColumn(
                "Cost Model Validation"
            ),
        },
    )

    # ---------------- CSV EXPORT ----------------

    if filtered_rows:
        import csv
        import io

        csv_buffer = io.StringIO()
        writer = csv.DictWriter(
            csv_buffer,
            fieldnames=filtered_rows[0].keys()
        )
        writer.writeheader()
        writer.writerows(filtered_rows)

        st.download_button(
            label="Download Filtered Results as CSV",
            data=csv_buffer.getvalue().encode("utf-8"),
            file_name=f"live_tenders_{datetime.now().strftime('%Y%m%d_%H%M')}.csv",
            mime="text/csv",
        )

    # ---------------- EXPLANATION ----------------

    with st.expander("How to verify that a tender is real"):
        st.markdown(
            """
1. Open the **Original Tender Source** link in the table.  
2. Compare the tender title, issuer, and closing date on the source portal.  
3. For Bus Operations, verify that the original tender is explicitly a **Gross Cost** contract.  
4. If the source does not clearly state a field, this dashboard should show `NOT SURE`, not a guessed value.  

The dashboard does not contain demo/sample tender data. It only reads
`data/live_tenders.json`, generated by the automated pipeline.
            """
        )


if __name__ == "__main__":
    main()
