"""
Tender Intelligence Agent Dashboard

This dashboard displays ONLY data generated by the real pipeline:
    data/live_tenders.json

No fake/demo/sample data is used.
"""

import csv
import io
import json
import os
from datetime import datetime, timezone

import streamlit as st

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LIVE_DATA_FILE = os.path.join(PROJECT_ROOT, "data", "live_tenders.json")
HEALTH_FILE = os.path.join(PROJECT_ROOT, "data", "health.json")

st.set_page_config(
    page_title="Tender Intelligence Agent",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded",
)


def load_json(path: str, fallback: dict):
    try:
        if not os.path.exists(path):
            return fallback

        with open(path, "r", encoding="utf-8") as file:
            return json.load(file)

    except Exception as error:
        return {
            **fallback,
            "status": "READ_ERROR",
            "message": f"Could not read {os.path.basename(path)}: {error}",
        }


def parse_time(timestamp: str):
    if not timestamp:
        return None

    try:
        return datetime.fromisoformat(
            str(timestamp).replace("Z", "+00:00")
        )
    except ValueError:
        return None


def human_time_ago(timestamp: str):
    parsed = parse_time(timestamp)

    if not parsed:
        return "Unknown"

    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)

    difference = datetime.now(timezone.utc) - parsed
    seconds = int(difference.total_seconds())

    if seconds < 0:
        return "Clock mismatch"

    if seconds < 60:
        return "Just now"

    if seconds < 3600:
        return f"{seconds // 60} minute(s) ago"

    if seconds < 86400:
        return f"{seconds // 3600} hour(s) ago"

    return f"{seconds // 86400} day(s) ago"


def build_rows(tenders: list[dict]):
    rows = []
    blocked_net_cost = 0
    blocked_invalid_category = 0

    allowed_categories = {
        "Charging point operations",
        "Solar",
        "Bus operations (gross cost only)",
        "Bus body building",
    }

    for tender in tenders:
        if not isinstance(tender, dict):
            continue

        category = str(tender.get("category", "")).strip()

        if category not in allowed_categories:
            blocked_invalid_category += 1
            continue

        is_net_cost = bool(tender.get("is_net_cost", False))

        # Final UI-level protection.
        if (
            category == "Bus operations (gross cost only)"
            and is_net_cost
        ):
            blocked_net_cost += 1
            continue

        source_url = str(tender.get("source_url", "")).strip()

        rows.append(
            {
                "Tender Title": tender.get("title", "NOT SURE"),
                "Category": category,
                "Closing Date": tender.get("closing_date", "NOT SURE"),
                "Issued By": tender.get("issued_by", "NOT SURE"),
                "Qualification Criteria": tender.get(
                    "qualification_criteria",
                    "NOT SURE",
                ),
                "Eligibility": tender.get(
                    "eligibility_status",
                    "NOT SURE",
                ),
                "Cost Model Validation": (
                    "✅ GROSS COST VERIFIED"
                    if category == "Bus operations (gross cost only)"
                    else "Not applicable"
                ),
                "Open Today": (
                    "🟢 YES"
                    if tender.get("is_open_now", False)
                    else "⚪ NOT CONFIRMED"
                ),
                "Confidence": tender.get("confidence", "LOW"),
                "Evidence": tender.get("evidence", "NOT SURE"),
                "Source URL": source_url,
                "Found At": str(tender.get("found_at", "NOT SURE"))[:19],
            }
        )

    return rows, blocked_net_cost, blocked_invalid_category


def main():
    live_payload = load_json(
        LIVE_DATA_FILE,
        {
            "data_source": "NO_LIVE_FILE",
            "generated_at": None,
            "record_count": 0,
            "tenders": [],
        },
    )

    health_payload = load_json(
        HEALTH_FILE,
        {
            "status": "NO_HEALTH_FILE",
            "message": "No pipeline health file exists yet.",
            "updated_at": None,
            "details": [],
        },
    )

    tenders = live_payload.get("tenders", [])

    if not isinstance(tenders, list):
        tenders = []

    rows, blocked_net_cost, blocked_invalid_category = build_rows(tenders)

    # ------------------------------------------------------
    # HEADER
    # ------------------------------------------------------

    st.title("Tender Intelligence Agent — Live Monitor")

    st.caption(
        "Autonomous monitoring for Charging Point Operations, Solar, "
        "Gross Cost Bus Operations, and Bus Body Building."
    )

    # ------------------------------------------------------
    # SIDEBAR HEALTH
    # ------------------------------------------------------

    with st.sidebar:
        st.header("System Health")

        status = str(health_payload.get("status", "UNKNOWN")).upper()
        health_message = health_payload.get("message", "No status message.")
        health_updated_at = health_payload.get("updated_at")

        if status == "SUCCESS":
            st.success("🟢 SYSTEM HEALTHY")
            st.write(health_message)

        elif status == "SUCCESS_ZERO_RESULTS":
            st.warning("🟡 SCAN COMPLETED — ZERO VERIFIED RESULTS")
            st.write(health_message)

        elif status == "FAILED":
            st.error("🔴 PIPELINE FAILED")
            st.write(health_message)

        elif status in {"NO_HEALTH_FILE", "READ_ERROR"}:
            st.warning("🟡 WAITING FOR FIRST SCAN")
            st.write(health_message)

        else:
            st.info(f"Status: {status}")
            st.write(health_message)

        st.caption(
            f"Last pipeline update: {human_time_ago(health_updated_at)}"
        )

        st.divider()

        st.subheader("Live Data Status")

        generated_at = live_payload.get("generated_at")

        if generated_at:
            st.success("🟢 REAL PIPELINE OUTPUT")
            st.caption(f"Last data scan: {human_time_ago(generated_at)}")
            st.caption(f"UTC: {generated_at}")

        else:
            st.warning("No real data file found yet.")

        st.divider()

        st.subheader("Rules Enforced")

        st.markdown(
            """
- ✅ Only 4 approved categories  
- ✅ Closed tenders excluded  
- ✅ Bus Net Cost tenders rejected  
- ✅ Gross Cost must be proven for bus operations  
- ✅ Unknown values shown as `NOT SURE`  
- ✅ Source URL retained for cross-verification  
- ✅ Failures visible here and in GitHub Actions  
            """
        )

        st.divider()

        st.markdown(
            "[Run pipeline from GitHub Actions](https://github.com/offoabhii/tender-intelligence-agent/actions)"
        )

    # ------------------------------------------------------
    # METRICS
    # ------------------------------------------------------

    total_open = sum(
        1 for row in rows
        if row["Open Today"] == "🟢 YES"
    )

    high_confidence = sum(
        1 for row in rows
        if str(row["Confidence"]).upper() == "HIGH"
    )

    categories_covered = len(
        set(row["Category"] for row in rows)
    )

    metric_1, metric_2, metric_3, metric_4 = st.columns(4)

    metric_1.metric("Verified Real Tenders", len(rows))
    metric_2.metric("Currently Open", total_open)
    metric_3.metric("Categories Covered", categories_covered)
    metric_4.metric("High Confidence", high_confidence)

    # ------------------------------------------------------
    # BUSINESS RULE NOTICE
    # ------------------------------------------------------

    st.divider()

    st.info(
        "🛡️ **Gross Cost policy:** A Bus Operations tender is displayed only "
        "when it is verified as a Gross Cost contract. Net Cost or unclear "
        "cost-model tenders are rejected before reaching this page."
    )

    if blocked_net_cost:
        st.warning(
            f"{blocked_net_cost} Net Cost Bus Operations tender(s) "
            "were blocked from display."
        )

    if blocked_invalid_category:
        st.caption(
            f"{blocked_invalid_category} non-approved category item(s) "
            "were filtered."
        )

    # ------------------------------------------------------
    # TABLE
    # ------------------------------------------------------

    st.subheader("Verified Open Tender Feed")

    if not rows:
        st.warning(
            "No verified real tenders are currently available from the latest scan."
        )

        st.markdown(
            """
This is not demo data and it is not a hidden failure.

Possible reasons:

1. The GitHub Actions workflow has not completed its first successful run.
2. Tavily returned no current tender documents for the approved categories.
3. The results were old, closed, irrelevant, or missing a verifiable closing date.
4. Bus-operation opportunities were Net Cost or had an unclear contract model,
   so they were correctly rejected.
5. A source/API issue occurred; check **System Health** and GitHub Actions logs.
            """
        )

        return

    categories = sorted(set(row["Category"] for row in rows))

    selected_categories = st.multiselect(
        "Filter by Category",
        options=categories,
        default=categories,
    )

    filtered_rows = [
        row for row in rows
        if row["Category"] in selected_categories
    ]

    st.dataframe(
        filtered_rows,
        use_container_width=True,
        hide_index=True,
        column_config={
            "Tender Title": st.column_config.TextColumn(
                "Tender Title",
                width="large",
            ),
            "Qualification Criteria": st.column_config.TextColumn(
                "Qualification Criteria",
                width="large",
            ),
            "Evidence": st.column_config.TextColumn(
                "Source Evidence",
                width="large",
            ),
            "Source URL": st.column_config.LinkColumn(
                "Original Tender Source",
                display_text="Open source",
                help="Use this link to cross-verify the tender.",
            ),
        },
    )

    # ------------------------------------------------------
    # CSV DOWNLOAD
    # ------------------------------------------------------

    if filtered_rows:
        csv_buffer = io.StringIO()

        writer = csv.DictWriter(
            csv_buffer,
            fieldnames=filtered_rows[0].keys(),
        )

        writer.writeheader()
        writer.writerows(filtered_rows)

        st.download_button(
            label="Download Verified Results as CSV",
            data=csv_buffer.getvalue().encode("utf-8"),
            file_name=(
                f"verified_live_tenders_"
                f"{datetime.now().strftime('%Y%m%d_%H%M')}.csv"
            ),
            mime="text/csv",
        )

    # ------------------------------------------------------
    # TRANSPARENCY
    # ------------------------------------------------------

    with st.expander("How to cross-verify a tender"):
        st.markdown(
            """
1. Click **Open source** for any tender.
2. Verify the title, issuer, and closing date against the original tender page.
3. For Bus Operations, verify the source explicitly states **Gross Cost**.
4. If a field is absent in the source, the system should display `NOT SURE`.
5. This dashboard contains no hardcoded sample tenders.
            """
        )


if __name__ == "__main__":
    main()
